import React from 'react';
import { motion } from 'framer-motion';
import { BiArrowBack, BiShieldQuarter, BiData, BiLockAlt, BiUserCheck } from 'react-icons/bi';

// Animation variants
const sectionVariants = {
  hidden: { opacity: 0, y: 20 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" } }
};

const itemVariants = {
  hidden: { opacity: 0, x: -20 },
  visible: { opacity: 1, x: 0, transition: { duration: 0.4 } }
};

const PrivacyPolicy = ({ setActivePage }) => {
  const Section = ({ icon: Icon, title, children }) => (
    <motion.section 
      className="mb-8 p-6 bg-black/20 rounded-xl border border-white/10 backdrop-blur-sm"
      variants={sectionVariants}
      initial="hidden"
      whileInView="visible"
      viewport={{ once: true }}
      whileHover={{ 
        boxShadow: "0 8px 32px rgba(78, 70, 236, 0.1)",
        borderColor: "rgba(255, 255, 255, 0.15)",
        y: -5,
        transition: { duration: 0.3 }
      }}
    >
      <div className="flex items-center mb-4">
        <Icon className="w-6 h-6 mr-3 text-indigo-400 flex-shrink-0" />
        <h2 className="text-xl md:text-2xl font-semibold text-white">{title}</h2>
      </div>
      <div className="space-y-4 text-gray-300 leading-relaxed text-sm md:text-base">
        {children}
      </div>
    </motion.section>
  );

  return (
    <div className="min-h-screen w-full bg-gradient-to-br from-gray-900 via-indigo-900 to-purple-900 text-white p-4 md:p-8 font-sans overflow-y-auto">
      <div className="max-w-4xl mx-auto">
        {/* Back Button */}
        <motion.button
          onClick={() => {
            console.log("PrivacyPolicy: Back button clicked");
            setActivePage('auth');
          }}
          className="mb-8 inline-flex items-center gap-2 px-4 py-2 bg-white/10 hover:bg-white/20 border border-white/10 rounded-lg text-sm font-medium transition-colors duration-200"
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0, transition: { duration: 0.5, ease: "easeOut" } }}
          whileHover={{ 
            scale: 1.05, 
            backgroundColor: "rgba(255, 255, 255, 0.15)",
            boxShadow: "0 4px 12px rgba(0, 0, 0, 0.2)"
          }}
          whileTap={{ scale: 0.95 }}
        >
          <BiArrowBack className="text-lg" />
          <span>Back to Sign In</span>
        </motion.button>

        <motion.h1 
          className="text-3xl md:text-5xl font-bold mb-4 text-center bg-clip-text text-transparent bg-gradient-to-r from-indigo-400 to-purple-400"
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          Privacy Policy
        </motion.h1>
        
        <motion.p
          className="text-gray-300 text-center mb-8 max-w-2xl mx-auto text-sm"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.2 }}
        >
          Last updated: October 3, 2025
        </motion.p>

        <Section icon={BiShieldQuarter} title="Introduction">
          <motion.div variants={itemVariants}>
            <p>
              Dred ("we", "our", or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, 
              use, and safeguard your information when you use our digital card wallet service.
            </p>
          </motion.div>
        </Section>

        <Section icon={BiData} title="Information We Collect">
          <motion.div variants={itemVariants}>
            <p className="mb-4">
              We collect minimal information necessary to provide our services:
            </p>
            <div className="space-y-3 ml-4">
              <div>
                <h3 className="font-semibold text-white mb-2">1. Google Authentication Data</h3>
                <ul className="list-disc list-inside space-y-1 ml-4">
                  <li>Email address</li>
                  <li>Profile picture</li>
                  <li>User ID (generated by Google)</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-white mb-2">2. Card Data (Encrypted)</h3>
                <ul className="list-disc list-inside space-y-1 ml-4">
                  <li>Card numbers, CVV, expiry dates (all encrypted)</li>
                  <li>Card nicknames and bank information</li>
                  <li>Bill payment information (encrypted)</li>
                </ul>
                <p className="text-sm text-indigo-200 mt-2 p-3 bg-indigo-900/30 rounded-lg">
                  <strong>Important:</strong> All sensitive card data is encrypted on your device before being stored. 
                  We cannot access or read your card information.
                </p>
              </div>
            </div>
          </motion.div>
        </Section>

        <Section icon={BiUserCheck} title="How We Use Your Information">
          <motion.div variants={itemVariants}>
            <p className="mb-4">
              Your information is used solely for the following purposes:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li><strong className="text-white">Authentication:</strong> Your email and profile picture are used to identify you and provide access to your account</li>
              <li><strong className="text-white">Service Provision:</strong> To store and retrieve your encrypted card data</li>
              <li><strong className="text-white">Account Management:</strong> To maintain your account and provide customer support if needed</li>
            </ul>
          </motion.div>

          <motion.div 
            variants={itemVariants}
            className="mt-4 p-4 bg-green-900/20 rounded-lg border border-green-500/30"
          >
            <h3 className="font-semibold text-white mb-2">What We DO NOT Do:</h3>
            <ul className="list-disc list-inside space-y-1 ml-4 text-green-200">
              <li>We do NOT use your email for marketing or promotional purposes</li>
              <li>We do NOT send newsletters or unsolicited communications</li>
              <li>We do NOT share your information with third parties for advertising</li>
              <li>We do NOT sell your data to anyone</li>
              <li>We do NOT access your encrypted card data</li>
            </ul>
          </motion.div>
        </Section>

        <Section icon={BiLockAlt} title="Data Security">
          <motion.div variants={itemVariants}>
            <p className="mb-4">
              We implement multiple layers of security to protect your information:
            </p>
            <div className="space-y-3 ml-4">
              <div>
                <h3 className="font-semibold text-white mb-2">Encryption</h3>
                <ul className="list-disc list-inside space-y-1 ml-4">
                  <li>AES-256 encryption for all sensitive data</li>
                  <li>End-to-end encryption - data is encrypted on your device before transmission</li>
                  <li>Your master password never leaves your device</li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold text-white mb-2">Access Controls</h3>
                <ul className="list-disc list-inside space-y-1 ml-4">
                  <li>Firebase security rules ensure only you can access your data</li>
                  <li>Account lockout mechanisms prevent brute force attacks</li>
                  <li>Google OAuth 2.0 for secure authentication</li>
                </ul>
              </div>
            </div>
          </motion.div>
        </Section>

        <Section icon={BiData} title="Data Storage and Retention">
          <motion.div variants={itemVariants}>
            <p className="mb-4">
              <strong className="text-white">Where Your Data is Stored:</strong>
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Your encrypted data is stored in Google Firebase Firestore</li>
              <li>Firebase servers are located in secure data centers with industry-standard protections</li>
              <li>Authentication is handled by Google's secure infrastructure</li>
            </ul>
          </motion.div>

          <motion.div variants={itemVariants} className="mt-4">
            <p className="mb-4">
              <strong className="text-white">Data Retention:</strong>
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Your data is retained as long as your account is active</li>
              <li>You can delete your cards at any time through the app</li>
              <li>If you delete your account, all associated data will be removed</li>
            </ul>
          </motion.div>
        </Section>

        <Section icon={BiShieldQuarter} title="Third-Party Services">
          <motion.div variants={itemVariants}>
            <p className="mb-4">
              We use the following third-party services to operate Dred:
            </p>
            <div className="space-y-3 ml-4">
              <div>
                <h3 className="font-semibold text-white mb-2">Google Firebase</h3>
                <p>Used for authentication, database, and hosting. Google's privacy policy applies to this service.</p>
              </div>
              <div>
                <h3 className="font-semibold text-white mb-2">Google OAuth</h3>
                <p>Used for secure sign-in. Google's privacy policy applies to the authentication process.</p>
              </div>
            </div>
            <p className="mt-4 text-sm">
              These services may collect their own data as described in their respective privacy policies. 
              We do not control and are not responsible for the privacy practices of these third parties.
            </p>
          </motion.div>
        </Section>

        <Section icon={BiUserCheck} title="Your Rights">
          <motion.div variants={itemVariants}>
            <p className="mb-4">You have the following rights regarding your personal data:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li><strong className="text-white">Access:</strong> You can access your account information at any time</li>
              <li><strong className="text-white">Deletion:</strong> You can delete your cards or entire account</li>
              <li><strong className="text-white">Correction:</strong> You can update your card information</li>
              <li><strong className="text-white">Data Portability:</strong> You can export your card data (in encrypted form)</li>
            </ul>
          </motion.div>
        </Section>

        <Section icon={BiData} title="Children's Privacy">
          <motion.div variants={itemVariants}>
            <p>
              Dred is not intended for use by individuals under the age of 18. We do not knowingly collect 
              personal information from children. If you are a parent or guardian and believe your child has 
              provided us with personal information, please contact us.
            </p>
          </motion.div>
        </Section>

        <Section icon={BiShieldQuarter} title="Changes to This Privacy Policy">
          <motion.div variants={itemVariants}>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of any changes by posting 
              the new Privacy Policy on this page and updating the "Last updated" date. You are advised to review 
              this Privacy Policy periodically for any changes.
            </p>
          </motion.div>
        </Section>

        <Section icon={BiUserCheck} title="Contact Us">
          <motion.div variants={itemVariants}>
            <p className="mb-3">
              If you have any questions about this Privacy Policy or our data practices, please contact us at:
            </p>
            <div className="bg-indigo-900/30 rounded-lg p-4 border border-indigo-500/30">
              <p className="text-indigo-200">
                <strong className="text-white">Email:</strong> aswinanand9020@gmail.com
              </p>
            </div>
          </motion.div>
        </Section>

        <motion.div
          className="mt-8 p-6 bg-indigo-900/20 rounded-xl border border-indigo-500/30 text-center"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <p className="text-gray-300 text-sm">
            By using Dred, you acknowledge that you have read and understood this Privacy Policy.
          </p>
        </motion.div>

        {/* Back to Sign In Button at Bottom */}
        <motion.div
          className="mt-8 text-center"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.5, delay: 0.3 }}
        >
          <motion.button
            onClick={() => setActivePage('auth')}
            className="px-6 py-3 bg-gradient-to-r from-indigo-500 to-purple-600 hover:from-indigo-600 hover:to-purple-700 
              text-white font-semibold rounded-xl shadow-md hover:shadow-lg transition-all duration-200"
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
          >
            Back to Sign In
          </motion.button>
        </motion.div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;

